name: Preview Build
on:
  workflow_dispatch:
    inputs:
jobs:
  build_all:
    name: Build Native & APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 1. ФИКС ПЕРЕНОСОВ СТРОК ДЛЯ LINUX
      - name: Fix line endings
        run: |
          find . -name "*.sh" -exec sed -i 's/\r$//' {} +
          sed -i 's/\r$//' run
          chmod +x run
          find . -type f -name "*.sh" -exec chmod +x {} +

      # 2. УСТАНОВКА GO И ANDROID SDK
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 3. СБОРКА ЯДРА (LIBCORE)
      - name: Native Build (LibCore)
        run: bash ./run lib core

      # ИЩЕМ И СОХРАНЯЕМ ГОТОВОЕ ЯДРО ДЛЯ ПК
      - name: Upload AAR for Android Studio
        uses: actions/upload-artifact@v4
        with:
          name: Core-Libraries
          path: ./**/*.aar

      # 4. СБОРКА ANDROID APK
      - name: Gradle Build
        env:
          BUILD_PLUGIN: none
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/25.0.8775105" >> local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          
          bash ./run init action gradle
          
          # Сборка ТОЛЬКО arm64 для скорости
          ./gradlew app:assemblePreviewRelease \
            -Pandroid.injected.abi=arm64-v8a \
            -x lint -x lintVitalPreviewRelease \
            --parallel --build-cache
          
          TARGET_DIR="app/build/outputs/target_apk"
          mkdir -p $TARGET_DIR
          find app/build/outputs/apk -name '*arm64-v8a*.apk' -exec cp {} $TARGET_DIR/ \;
          echo "APK_DIR=$TARGET_DIR" >> $GITHUB_ENV

      # 5. ХАК ДЛЯ ИСПРАВЛЕНИЯ ОШИБКИ ПОДПИСИ
      - name: Fix Android Build Tools Path
        run: |
          LATEST_VERSION=$(ls $ANDROID_HOME/build-tools | sort -V | tail -n 1)
          echo "Используем версию $LATEST_VERSION как замену для 29.0.3"
          sudo ln -s $ANDROID_HOME/build-tools/$LATEST_VERSION $ANDROID_HOME/build-tools/29.0.3

      # 6. ПОДПИСЬ APK
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ${{ env.APK_DIR }}
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      # 7. ВЫГРУЗКА ГОТОВОГО ФАЙЛА
      - uses: actions/upload-artifact@v4
        with:
          name: NekoBox-arm64-v8a-Signed
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
